# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(835, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.createBomb_btn = QtWidgets.QPushButton(self.centralwidget)
        self.createBomb_btn.setGeometry(QtCore.QRect(20, 10, 211, 61))
        self.createBomb_btn.setStyleSheet("font: 16pt \"OCR A Extended\";")
        self.createBomb_btn.setObjectName("createBomb_btn")
        self.strikes_lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.strikes_lcdNumber.setGeometry(QtCore.QRect(700, 10, 41, 51))
        self.strikes_lcdNumber.setDigitCount(1)
        self.strikes_lcdNumber.setObjectName("strikes_lcdNumber")
        self.strikes_lbl = QtWidgets.QLabel(self.centralwidget)
        self.strikes_lbl.setGeometry(QtCore.QRect(580, 10, 141, 51))
        self.strikes_lbl.setStyleSheet("font: 14pt \"OCR A Extended\";")
        self.strikes_lbl.setObjectName("strikes_lbl")
        self.strike_btn = QtWidgets.QPushButton(self.centralwidget)
        self.strike_btn.setGeometry(QtCore.QRect(750, 20, 41, 41))
        self.strike_btn.setStyleSheet("font: 10pt \"OCR A Extended\";")
        self.strike_btn.setObjectName("strike_btn")
        self.modules_tab = QtWidgets.QTabWidget(self.centralwidget)
        self.modules_tab.setGeometry(QtCore.QRect(40, 110, 751, 441))
        self.modules_tab.setTabShape(QtWidgets.QTabWidget.TabShape.Triangular)
        self.modules_tab.setTabsClosable(False)
        self.modules_tab.setTabBarAutoHide(False)
        self.modules_tab.setObjectName("modules_tab")
        self.simpleWires_tab = QtWidgets.QWidget()
        self.simpleWires_tab.setObjectName("simpleWires_tab")
        self.modules_tab.addTab(self.simpleWires_tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.modules_tab.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 835, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.modules_tab.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.createBomb_btn.setText(_translate("MainWindow", "Create Bomb"))
        self.strikes_lbl.setText(_translate("MainWindow", "Strikes"))
        self.strike_btn.setText(_translate("MainWindow", "+1"))
        self.modules_tab.setTabText(self.modules_tab.indexOf(self.simpleWires_tab), _translate("MainWindow", "Simple Wires"))
        self.modules_tab.setTabText(self.modules_tab.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
